### ISSUE TITLE
how to run app？

### ISSUE THREAD

**Issue by sunxiao1983** [Luxi-Zhao/chinese-landscape-painting-stylization#1]
there is docker image for dockerfile to run code？i don't konw to run app thanks。

**Comment by Luxi-Zhao** [comment]
Hi there! This project hasn't been made into an app yet so there isn't a docker image. To use the model you could run this colab notebook [pix2pixSketch2PaintPredict.ipynb](https://colab.research.google.com/github/Luxi-Zhao/chinese-landscape-painting-stylization/blob/master/src/pix2pixSketch2PaintPredict.ipynb).
